workflows:
  android-build:
    name: Smart Day Planner X Build
    environment:
      java: 17

    scripts:
      - name: Fix Gradle permission
        script: chmod +x gradlew

      - name: Build Debug APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
